version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:80"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=urlshort;Uid=urlshort;Pwd=alskjdfa@alskdjfAAAb12;

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: urlshort
      MYSQL_USER: urlshort
      MYSQL_PASSWORD: alskjdfa@alskdjfAAAb12
      MYSQL_ROOT_PASSWORD: rootpassword123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "urlshort",
          "-palskjdfa@alskdjfAAAb12"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:

networks:
  default:
    name: app-network
    driver: bridge
