services:
  backend:
    build: ./backend
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=urlshort;Username=urlshort;Password=alskjdfa@alskdjfAAAb12
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API=${API}
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshort
      POSTGRES_USER: urlshort
      POSTGRES_PASSWORD: alskjdfa@alskdjfAAAb12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshort"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data:

networks:
  default:
    name: app-network
    driver: bridge
