name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and clean up containers
        run: |
          docker compose -p url-shortener down --remove-orphan
          docker network prune -f

      - name: Pull latest images
        run: docker compose -p url-shortener pull

      - name: Rebuild and restart containers
        run: docker compose -p url-shortener up -d --build --remove-orphans
