name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify files
        run: ls -la

      - name: Run Docker Compose
        run: |
          docker-compose up -d
