name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup previous deployment
        run: |
          docker compose -p url-shortener down --volumes --remove-orphans --rmi all
          docker network prune -f

      - name: Pull latest images
        run: docker compose -p url-shortener pull

      - name: Build and start containers
        run: docker compose -p url-shortener up -d --build --remove-orphans
