name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and remove containers
        run: docker compose -p url-shortener down

      - name: Rebuild and start containers
        run: docker compose -p url-shortener up -d --build
